<?php
/**
 * @category   Calliweb
 * @package    Calliweb_Rma
 * @author	   Calliweb <office@calliweb.fr>
 * @copyright  Copyright (c) 2014 Calliweb (http://www.calliweb.fr)
 * @license    http://creativecommons.org/publicdomain/zero/1.0/ Creative Commons CC0
 */
 
 $_customerHelper = $this->helper('customer');
 $_rmas = $this->getRmas();
 
?>
<div class="page-title">
    <h1><?php echo $this->__('Return Merchandise Agreements') ?></h1>
</div>

<?php if($_rmas->getSize()): ?>
<?php echo $this->getChildHtml('pager'); ?>
	<table class="data-table" id="rmas">
		<col width="1" />
		<col width="1" />
		<col width="1" />
		<col />
		<col />
		<col width="1" />
		<thead>
			<tr>
				<th><?php echo $this->__('Return #') ?></th>
				<th><?php echo $this->__('Order #') ?></th>
				<th><?php echo $this->__('Date') ?></th>
				<th><?php echo $this->__('Object') ?></th>
				<th><?php echo $this->__('Status') ?></th>
				<th></th>
			</tr>
		</thead>
		<?php foreach($_rmas as $_rma): ?>
		<tbody>
			<tr class="border">
				<td><?php echo $_rma->getId() ?></td>
				<td><?php echo $_rma->getOrder()->getRealOrderId() ?></td>
				<td><?php echo $this->formatDate($_rma->getCreatedAt()) ?></td>
				<td><?php echo $_rma->getSubject() ?></td>
				<td><?php echo $_rma->getState() ?></td>
				<td class="a-center nobr"><a href="<?php echo $this->getRmaUrl($_rma) ?>"><?php echo $this->__('View request') ?></a></td>
			</tr>
		</tbody>
		<?php endforeach; ?>
	</table>
	<script type="text/javascript">decorateTable('rmas', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php echo $this->getChildHtml('pager'); ?>
<?php else: ?>
	<p><?php echo $this->__('You have made no requests for return.'); ?></p>
<?php endif; ?>

<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->getUrl('customer/account/') ?>"><small>&laquo; </small><?php echo $_customerHelper->__('Back') ?></a></p>
	<?php if($this->canReturnOrders()): ?>
	<button type="button" onclick="window.location='<?php echo $this->getReturnUrl() ?>';" class="button"><span><span><?php echo $this->__('New request for return') ?></span></span></button>
	<?php endif; ?>
</div>
