<?php
/**
 * @category   Calliweb
 * @package    Calliweb_Rma
 * @author	   Calliweb <office@calliweb.fr>
 * @copyright  Copyright (c) 2014 Calliweb (http://www.calliweb.fr)
 * @license    http://creativecommons.org/publicdomain/zero/1.0/ Creative Commons CC0
 */

$_helper = $this->helper('rma');
$parentItem = $this->getItem();
$items = array_merge(array($parentItem), $parentItem->getChildrenItems());
$_count = count ($items);
$_index = 0;
$_prevOptionId = ''; ?>

<?php foreach ($items as $_item): ?>

<?php if($this->getItemOptions() || $parentItem->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php if ($_item->getParentItem()): ?>
    <?php $attributes = $this->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr<?php if ($_item->getLastRow()) echo 'class="last"'; ?>>
        <td><div class="option-label"><?php echo $attributes['option_label'] ?></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif; ?>
<?php endif; ?>
<tr<?php echo (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?> id="order-item-row-<?php echo $_item->getId() ?>">

    <?php if (!$_item->getParentItem()): ?>
    <td><h3 class="product-name"><?php echo $this->htmlEscape($_item->getName()) ?></h3></td>
    <?php else: ?>
    <td><div class="option-value"><?php echo $this->getValueHtml($_item)?></div></td>
    <?php endif; ?>
    <td><?php echo $this->htmlEscape(Mage::helper('core/string')->splitInjection($_item->getSku())) ?></td>
	<?php if (!$_item->getParentItem()): ?>
	<td>&nbsp;</td>
	<?php else: ?>
	<td>
	<?php if($_item->getIsQtyDecimal()): ?>
		<div class="input-box">
			<input type="text" id="rma_order_<?php echo $_item->getOrderId() ?>_<?php echo $_item->getId() ?>" name="order_<?php echo $_item->getOrderId() ?>[<?php echo $_item->getId() ?>]" title="<?php echo $this->__("Returned qty") ?>" class="validate-number validate-number-range number-range-0-<?php echo ceil($_helper->getQtyToReturn($_item)) ?>" value="" />
			<span class="comment"><?php echo $this->__('Max: %s', $_helper->getQtyToReturn($_item)); ?></span>
		</div>	
	<?php else: ?>
		<div class="input-box">
			<select id="rma_order_<?php echo $_item->getOrderId() ?>_<?php echo $_item->getId() ?>" name="order_<?php echo $_item->getOrderId() ?>[<?php echo $_item->getId() ?>]" title="<?php echo $this->__("Returned qty") ?>">
				<option value=""><?php echo $this->helper('core')->__('-- Please Select --') ?></option>
				<?php for($_i=1; $_i<=$_helper->getQtyToReturn($_item); $_i++): ?>
				<option value="<?php echo $_i ?>"><?php echo $_i ?></option>
				<?php endfor; ?>
			</select>
		</div>
	<?php endif ?>
	</td>
	<?php endif; ?>
</tr>
<?php endforeach; ?>

<?php if ($_showlastRow): ?>
<tr class="border">
    <td>
        <?php if($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
            <?php if (!$this->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                    <?php echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="truncated_full_value">
                        <dl class="item-options">
                            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd><?php echo $this->htmlEscape( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) ) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php echo $this->htmlEscape($_item->getDescription()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif; ?>