<?php
/**
 * @category   Calliweb
 * @package    Calliweb_Rma
 * @author	   Calliweb <office@calliweb.fr>
 * @copyright  Copyright (c) 2014 Calliweb (http://www.calliweb.fr)
 * @license    http://creativecommons.org/publicdomain/zero/1.0/ Creative Commons CC0
 */

$_item = $this->getItem();
$_helper = $this->helper('rma');

?>
<tr class="border" id="order-item-row-<?php echo $_item->getId() ?>">
	<td>
		<h3 class="product-name"><?php echo $this->htmlEscape($_item->getName()) ?></h3>
		<?php if($_options = $this->getItemOptions()): ?>
		<dl class="item-options">
		<?php foreach ($_options as $_option) : ?>
			<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
			<?php if (!$this->getPrintStatus()): ?>
				<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
				<dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
				<?php echo $_formatedOptionValue['value'] ?>
				<?php if (isset($_formatedOptionValue['full_view'])): ?>
					<div class="truncated_full_value">
						<dl class="item-options">
							<dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
							<dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
						</dl>
					</div>
				<?php endif; ?>
				</dd>
			<?php else: ?>
				<dd>
					<?php echo nl2br($this->htmlEscape( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) )) ?>
				</dd>
			<?php endif; ?>
		<?php endforeach; ?>
		</dl>
		<?php endif; ?>
		<?php $addtInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
		<?php if ($addtInfoBlock) :?>
			<?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
		<?php endif; ?>
		<?php echo $this->htmlEscape($_item->getDescription()) ?>
	</td>
	<td>
		<?php echo $this->htmlEscape(Mage::helper('core/string')->splitInjection($this->getSku())) ?>
	</td>
	<td>
	<?php if($_item->getIsQtyDecimal()): ?>
		<div class="input-box">
			<input type="text" id="rma_order_<?php echo $_item->getOrderId() ?>_<?php echo $_item->getId() ?>" name="order_<?php echo $_item->getOrderId() ?>[<?php echo $_item->getId() ?>]" title="<?php echo $this->__("Returned qty") ?>" class="validate-number validate-number-range number-range-0-<?php echo ceil($_helper->getQtyToReturn($_item)) ?>" value="" />
			<span class="comment"><?php echo $this->__('Max: %s', $_helper->getQtyToReturn($_item)); ?></span>
		</div>	
	<?php else: ?>
		<div class="input-box">
			<select id="rma_order_<?php echo $_item->getOrderId() ?>_<?php echo $_item->getId() ?>" name="order_<?php echo $_item->getOrderId() ?>[<?php echo $_item->getId() ?>]" title="<?php echo $this->__("Returned qty") ?>">
				<option value=""><?php echo $this->helper('core')->__('-- Please Select --') ?></option>
				<?php for($_i=1; $_i<=$_helper->getQtyToReturn($_item); $_i++): ?>
				<option value="<?php echo $_i ?>"><?php echo $_i ?></option>
				<?php endfor; ?>
			</select>
		</div>
	<?php endif ?>
	</td>
</tr>