<?php
/**
 * @category   Calliweb
 * @package    Calliweb_Rma
 * @author	   Calliweb <office@calliweb.fr>
 * @copyright  Copyright (c) 2014 Calliweb (http://www.calliweb.fr)
 * @license    http://creativecommons.org/publicdomain/zero/1.0/ Creative Commons CC0
 */
 
 $_order = $this->getOrder();

?>
<?php if($this->canReturnOrder($_order)): ?>
<span class="separator">|</span>
<a href="<?php echo $this->getReturnUrl($_order); ?>" class="link-rma"><?php echo $this->__('Return products') ?></a>
<?php endif; ?>